chore: add Windows job for building and caching dependencies in multi_platform_ci.yml to improve CI efficiency

diff --git a/.github/workflows/multi_platform_ci.yml b/.github/workflows/multi_platform_ci.yml
--- a/.github/workflows/multi_platform_ci.yml
+++ b/.github/workflows/multi_platform_ci.yml
@@ -83,9 +83,35 @@ jobs:
 
   ## ------------------ Windows Job ------------------ ##
 
+  windows-x86_64-build-deps:
+    name: Build and Cache Dependencies
+    runs-on: windows-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Install Build Tools
+        run: choco install -y 7zip make
+
+      - name: Set up MSVC Developer Command Prompt
+        uses: ilammy/msvc-dev-cmd@v1
+
+      - name: Cache Dependencies
+        id: cache-deps
+        uses: actions/cache@v4
+        with:
+          path: |
+            .fw_dependencies
+          key: ${{ runner.os }}-${{ runner.arch }}-deps-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}
+
+      - name: Install Dependencies
+        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
+        run: make deps-install-release
+
   test_windows_x86_64:
     name: Test on Windows (x86_64)
     runs-on: windows-latest
+    needs: windows-x86_64-build-deps
 
     steps:
       - name: Checkout repository
@@ -102,13 +128,12 @@ jobs:
         uses: actions/cache@v4
         with:
           path: |
-            cmake/install
             .fw_dependencies
-          key: ${{ runner.os }}-${{ runner.arch }}-deps-v2-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}
+          key: ${{ runner.os }}-${{ runner.arch }}-deps-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}
 
-      - name: Install Dependencies
+      - name: Fail if cache not found
         if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
-        run: make deps-install-release
+        run: echo "Cache not found, the build-deps job should have created it." && exit 1
 
       - name: Build and Test
         # The environment is now correctly configured for your presets (MSVC + Ninja).
